### ISSUE TITLE
Compile *ListAbstract fails due to missing dependency on gs-collections.jar [Version 17.0.1]

### ISSUE THREAD

**Issue by henohenotsuyoshi** [goldmansachs/reladomo#146]
Looks like maven is not able to resolve dependency on gs-collections.jar when running build on latest version 17.0.1. I believe everyone can replicate this problem by changing reladomo version in reladomo/samples/reladomo-sample-simple/build.gradle to 17.0.1.

> tsuyoshi@tsuyoshi-XPS-13-9360:~/Downloads/reladomo/samples/reladomo-sample-simple$ gradle build
> :genReladomo
> :compileJava
> /home/tsuyoshi/Downloads/reladomo/samples/reladomo-sample-simple/build/generated-sources/reladomo/sample/domain/PersonListAbstract.java:104: error: package com.gs.collections.impl.list.mutable does not exist
> 		return com.gs.collections.impl.list.mutable.ListAdapter.adapt(this);
> 		                                           ^
> /home/tsuyoshi/Downloads/reladomo/samples/reladomo-sample-simple/build/generated-sources/reladomo/sample/domain/ObjectSequenceListAbstract.java:104: error: package com.gs.collections.impl.list.mutable does not exist
> 		return com.gs.collections.impl.list.mutable.ListAdapter.adapt(this);
> 		                                           ^
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 2 errors
> :compileJava FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':compileJava'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED

**Comment by itohiro73** [comment]
Reladomo 17.x removed internal dependency on gs-collections.jar so if you still want to use asGscList() you'd need to add gs-collections dependency explicitly by yourself. Or you could use `generateEcListMethod: "true"` instead. I'd recommend to take the latter path if possible. 

Let me update sample project's reladomo version and make it use EC instead.
